plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'jacoco'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.wendorochena.poetskingdom"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable = true
            enableAndroidTestCoverage = true
            enableUnitTestCoverage = true
            testCoverageEnabled = true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
        compose true
    }
    dataBinding {
        enabled = true
    }
    packagingOptions {
        //needs to be commented out in order to use layout inspector
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
        resources.excludes.add("META-INF/**")
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_compiler_version
    }
    sourceSets {
        androidTest {
            res.srcDirs("src/androidTest/res")
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
        unitTests {
            includeAndroidResources = true
        }
        unitTests.all {
            jacoco {
                enabled = true
                includeNoLocationClasses = true // Include all classes for coverage
            }
        }
    }
    namespace 'com.wendorochena.poetskingdom'
}
jacoco {
    toolVersion = "0.8.12" // Define the JaCoCo version
}
// Filter out unnecessary files from code coverage
def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*',
                  '**/Manifest*.*', 'android/**/*.*', 'androidx/*.*']

// Apply JaCoCo settings to all unit test tasks
tasks.withType(Test).configureEach {
    jacoco {
        enabled = true
        destinationFile = layout.buildDirectory.file("jacoco/${name}.exec").get().asFile
    }
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*'] // Exclude unwanted classes
}
// Task to generate JaCoCo code coverage report
tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn('testDebugUnitTest')
    dependsOn("createDebugCoverageReport")

    reports{
        xml.required = true
        html.required = true
    }
    def debugTree = fileTree(dir: "${rootProject.layout.buildDirectory.asFile.get()}/intermediates/classes/debug", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom(files([mainSrc]))
    classDirectories.setFrom(files([debugTree]))

    // Specify execution data files that JaCoCo will use to generate coverage report
    executionData.setFrom(fileTree(dir: "${rootProject.layout.buildDirectory.asFile.get()}", includes: [
            "jacoco/*.exec",
            "outputs/code_coverage/debugAndroidTest/connected/*coverage.ec"
    ]))
}


dependencies {

    implementation 'androidx.navigation:navigation-compose:2.6.0'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation("io.coil-kt.coil3:coil-compose:3.0.4")
    implementation 'com.github.Dhaval2404:ColorPicker:2.3'
    implementation("com.github.skydoves:colorpicker-compose:1.1.2")
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.6.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.6.0'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.7.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
    implementation 'androidx.activity:activity-compose:1.7.2'
    implementation 'androidx.compose.ui:ui:1.8.3'
    implementation 'androidx.compose.ui:ui-graphics:1.7.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose-android:2.8.7'
    implementation 'androidx.activity:activity:1.10.0'
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4:1.7.6'
    debugImplementation 'androidx.compose.ui:ui-tooling:1.7.7'
    def composeBom = platform('androidx.compose:compose-bom:2025.01.01')
    implementation composeBom
    androidTestImplementation composeBom
    implementation 'androidx.compose.material:material'
    implementation 'com.github.bumptech.glide:compose:1.0.0-alpha.1'
    implementation 'com.squareup.picasso:picasso:2.71828'
    testImplementation "io.mockk:mockk:1.13.16"
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.test.ext:junit-ktx:1.1.5'
    implementation 'androidx.test.espresso:espresso-contrib:3.5.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.5.1')
    androidTestImplementation('androidx.test:runner:1.5.2')
    androidTestImplementation('androidx.test:rules:1.5.0')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.skydoves:colorpickerview:2.2.4'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.2.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:4.1.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.0-Beta'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.14.2'
    debugImplementation 'androidx.compose.ui:ui-test-manifest:1.7.7'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.7.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
}